317 cypress navigation
stiftelsen-effekt/main-site pull request #346
Opened 2022-07-25 07:20 UTC by philiphand

2022-07-25 17:53 UTC, philiphand commented
Alt klart her nå! @fellmirr

2022-07-26 15:15 UTC, fellmirr requested changes
Good stuff, if we add a stub for newsletter signups this looks very promising :)

2022-07-26 15:15 UTC, fellmirr commented on cypress/e2e/navigation.js
> +        cy.get("[data-cy=newsletter-submit]").click()
This should be stubbed right, so we don't make a whole bunch of signups? :P

2022-07-28 10:10 UTC, fellmirr approved these changes
:+1:

2022-07-28 10:10 UTC, merged