Add custom properties for swish ans autogiro
stiftelsen-effekt/main-site pull request #934
Opened 2024-02-12 09:12 UTC by EliseAndresen

_Issue description here_

- closes #933 

---

Tested on devices

- [ ] Desktop 💻
- [ ] Mobile 📱

Tests

- [ ] All tests are running ✔️
- [ ] Test are updated 🧪
- [ ] Code Review 👩‍💻
- [ ] QA 👌

Checkpoints

_Check these to flag for a more thurough review, as they could be potentially breaking changes_

- [ ] Packages updated
- [ ] Other infrastructure updated (such as node version or similar)

⏲️ Time spent on CR:

⏲️ Time spent on QA:

2024-02-13 10:14 UTC, fellmirr requested changes
Looks pretty straight forward! Just the one small thing with wrong form.

2024-02-13 10:14 UTC, fellmirr commented on components/shared/components/Widget/components/panes/PaymentPane/AvtaleGiro/RecurringForm.tsx
> +    plausible("DraftAutogiro");
Should probably be in the AutoGiro form

2024-02-13 11:34 UTC, EliseAndresen commented on components/shared/components/Widget/components/panes/PaymentPane/AvtaleGiro/RecurringForm.tsx
> +    plausible("DraftAutogiro");
This has been reset :D

2024-02-15 19:30 UTC, fellmirr requested changes
Very small fix to required, otherwise seems to work!

2024-02-15 19:30 UTC, fellmirr commented on components/shared/components/Widget/components/panes/PaymentPane/AvtaleGiro/RecurringForm.tsx
> +    plausible("DraftAvtaleGiro");
Denne burde ikke endres, vi kan bare la den være som den er med liten g

2024-02-16 09:12 UTC, merged